---

- hosts: all
  become: true
  tasks:

  - name: for apt
    apt:
      name: nmap
      state: absent
    when: ansible_distribution == "Linux Mint"

  - name: for redhat
    yum:
      name: nmap
      state: absent
    when: ansible_distribution == "RedHat"

  - name: For arch
    pacman:
         name: nmap
         state: latest
    when: ansible_distribution =="Archlinux"
